services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan migrate --force && apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:LpA6WlKhUUFkAiQ7hEvUWJjkgQMP6rwqEqNd6FR8j20=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: maglev.proxy.rlwy.net
      - key: DB_PORT
        value: 16273
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: JMoyjpnynEsQUgGWezWQfbnxdIicyPSq
